baseURL = "https://blog.basix.tech/"
languageCode = "en-gb"
title = "Basix Blog"

defaultContentLanguage = "ko"
theme = "stack"

[permalinks]
blog = "/p/:slug/"
page = "/:slug/"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200