[[main]]
identifier = "home"
name = "Home"
url = "/en"
weight = -100
pre = "home"
[[main]]
identifier = "archives"
name = "Archives"
url = "/en/archives"
weight = -70
pre = "archives"
[[main]]
identifier = "search"
name = "Search"
url = "/en/search"
weight = -60
pre = "search"