[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"
[[main]]
identifier = "archives"
name = "Archives"
url = "archives"
weight = -70
pre = "archives"
[[main]]
identifier = "search"
name = "Search"
url = "search"
weight = -60
pre = "search"