mainSections = ["blog"]
rssFullContent = true

[comments]
enabled = true
provider = "utterances"

[comments.utterances]
repo = "BasixKOR/basix-blog"
issueTerm = "pathname"
label = "blog-comment"
theme = "preferred-color-scheme"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[sidebar]
avatar = "img/basixlab.png"

[article.license]
enabled = true 
default = "CC BY-NC-SA 4.0"

[widgets]
    enabled = ['search', 'archives', 'tag-cloud']
    [widgets.archives]
        limit = 5
        path = "archives"       
    [widgets.tagCloud]
        limit = 10