backend:
  name: git-gateway
local_backend: true
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
i18n: 
  structure: multiple_files
  locales: [en, ko]
  default_locale: ko
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    i18n: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    format: yaml-frontmatter
    fields:
      - label: Draft
        name: draft
        widget: boolean
        i18n: true
        default: true 
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Description
        name: description
        widget: string
        i18n: true
      - label: Publish Date
        name: date
        widget: datetime
        i18n: duplicate
      - label: Featured Image
        name: Image
        widget: image
        required: false
        i18n: duplicate
      - label: Tags
        name: tags
        widget: list
        i18n: true
      - label: Categories
        name: categories
        widget: list
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: true